### ISSUE TITLE
Where to ask feature questions?

### ISSUE THREAD

**Issue by birds-swim** [volitank/nala#12]
Sorry!  I'm new to GitHub and I'm still learning.  But I wanted to know if `nala` supports automatic Snapper snapshots and `apt-transport-tor`?  Those features are really, really important to me.

**Comment by Eason-S-Lu** [comment]
I guess try [Gitlab](https://gitlab.com/volian/nala/-/issues), but honestly, I don't know either.

**Comment by volitank** [comment]
Yes the link @Eason-S-Lu provided is correct for feature requests. I don't check the Github very often.

However, the automatic Snapper should work fine. I believe there is a configuration to set this up for apt, and it would work with Nala if it works with apt. I haven't personally tested it though.

**Comment by Eason-S-Lu** [comment]
> Yes the link @Eason-S-Lu provided is correct for feature requests. I don't check the Github very often.
> 
> However, the automatic Snapper should work fine. I believe there is a configuration to set this up for apt, and it would work with Nala if it works with apt. I haven't personally tested it though.

So I guess this is closed?

**Comment by volitank** [comment]
Yea I think so.

You should configure apt to work with smapper. I know there are some guides out there for it. At this point it should work with Nala.

If there are any issues feel free to open a new issue about it in gitlab. I'll see it faster.
