### ISSUE TITLE
Undesirable localization enforcing in prompt

### ISSUE THREAD

**Issue by mihael-stormrage** [volitank/nala#15]
I'm using locale other than en_US and here is what I've encountered:
```
Do you want to continue? [Д/н] y
Not a valid choice kiddo
Do you want to continue? [Д/н] Д
```
While apt accepts the first, even while localized.
Please, add default `y/n` anyways

**Comment by volitank** [comment]
I'm pretty sure I fixed this in one of the later versions. What version of Nala are you on?
