### ISSUE TITLE
Multiple errors in recent days after weeks of Nala working fine here in the latest Ubuntu LTS.

### ISSUE THREAD

**Issue by TofuWand** [volitank/nala#16]
nala
Traceback (most recent call last):
  File "/usr/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/usr/lib/python3/dist-packages/nala/__main__.py", line 30, in <module>
    import nala.fetch as _fetch  # pylint: disable=unused-import
  File "/usr/lib/python3/dist-packages/nala/fetch.py", line 37, in <module>
    import typer
  File "/usr/lib/python3/dist-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/usr/local/lib/python3.10/dist-packages/click/termui.py)
![Screenshot from 2023-06-26 20-20-32](https://github.com/volitank/nala/assets/117850518/3103b81b-fbfb-417c-a73c-75f581ab7e93)

...

Also, great sonic image for Nala! Haha. I know it was a cat, before. Now, it's a character I grew up with as a kid born in 89, as a 90s kid. ^_^ <3 🤝

**Comment by volitank** [comment]
Looks like it's not using the click library in the system directory. Using `usr/local/lib/python3.10/dist-packages/click/termui.py`.

This likely means that something you have installed with pip requires a version of click that is incompatible. Stupid Python problems. Is there anything you might have installed using pip that brought this in?

To fix is running `sudo pip uninstall click` will fix nala, but might break whatever pip program is using it.

**Comment by TofuWand** [comment]
Thanks! Yeah, quite problematic with that, but thankfully it got resolved
after I was assisted on GitLab. I read on the software page that GitLab is
faster to get a response than here for Nala. The issue got resolved a while
back. I do appreciate your time, that you were wanting to help me, and the
nice message that you sent. 😅🤝😌🤓😎 Have a great day/night! Ciao. :3
