### ISSUE TITLE
fetch action should allow dry-run without writing nala-sources.list

### ISSUE THREAD

**Issue by milosz** [volitank/nala#3]
Hello,

From my point of view fetch action should implement `--dry-run` option to only determine and display best servers without writing `nala-sources.list` file.

Thanks for such useful app!
Milosz

**Comment by volitank** [comment]
Hello, thanks for using nala. There is some discussion in on of our gitlab issues related to this.

The TL:DR is that we're probably considering changing how fetch works from a user's prespective. With the proposed changes I don't believe a `--dry-run` switch would be necessary. Basically it would do every thing, let you choose from a list of the fastest mirrors (potentially), print what is about to happen and then ask you if you'd like to overwrite

https://gitlab.com/volian/nala/-/issues/44

**Comment by milosz** [comment]
Thanks for info. Feel free to close this ticket. I will follow provided discussion.

**Comment by volitank** [comment]
Going to close now. I hope you found my solution adequate.
