### ISSUE TITLE
Arm64 not available from Repo anymore

### ISSUE THREAD

**Issue by ameinild** [volitank/nala#36]
Hi. I'm using Ubuntu on a Raspberry Pi, and currently running Nala 0.14.

With the new version 0.15, there is no Arm64 version in the repos anymore. As evident, only an Amd64 version exist.

Will there be an Arm64 version available in the Repos in the future? Else I'll have to consider some other installation option. 😬

![Volian_repo](https://github.com/volitank/nala/assets/434479/eca734f3-16cc-4565-a258-d53f41af09bc)

**Comment by volitank** [comment]
Hi the repo should work for you now. Please reopen if this issue is still happening.
