### ISSUE TITLE
Nala on debian troff error on autocomplete

### ISSUE THREAD

**Issue by XxUnknownxX9037** [volitank/nala#37]
On Nala, on my debian system, when i try to autocomplete with tab, it spits out this error. Any fixes?
![image](https://github.com/volitank/nala/assets/82404917/c3e0aa24-fd94-4333-ac55-cff8ddf87c20)

**Comment by brockar** [comment]
same for me.
Debian Trixie. 
Terminal: kitty / Gnome terminal  
nala version: nala 0.15.0
![2024-01-30_11-52](https://github.com/volitank/nala/assets/55927935/8d10b29f-4106-4316-bc00-96f3c3220b60)

**Comment by brockar** [comment]
Solved. 
Download here and install with `sudo apt install ./nala_0.15.1_all.deb`
[link](http://ftp.debian.org/debian/pool/main/n/nala/nala_0.15.1_all.deb)

--- 
By Volitank on discord:
"Yea, I pushed a hotfix for that in 0.15.1
It should be in Sid by now, but testing will take a bit to migrate"

**Comment by volitank** [comment]
Thanks @brockar 

Going to close this one.
