### ISSUE TITLE
Nala Python Error On Use after Installation

### ISSUE THREAD

**Issue by TheBrokenG0d** [volitank/nala#41]
I'm currently on Debian 12 and installed Nala via [volian-scar](https://gitlab.com/volian/nala/-/wikis/Installation#volian-scar)

Run I try to run any Nala command I get 

`Traceback (most recent call last):
  File "/usr/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/usr/lib/python3/dist-packages/nala/__init__.py", line 67, in <module>
    import debian.debian_support  # isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'debian'`

I can provide further info if needed.

**Comment by volitank** [comment]
Very interesting. This is listed in the control file, so the dependency should have been gotten. `nala --version` shows `v0.15.1`?

If it wasn't installed, this should resolve it `apt install python3-debian`

**Comment by TheBrokenG0d** [comment]
So I already have `python3-debian` version `0.1.49`
If I try to run `nala --version` I get the same error message as in my first post. 
But if I run 
```
apt policy nala
nala:
  Installed: 0.15.1
  Candidate: 0.15.1
  Version table:
 *** 0.15.1 500
        500 https://deb.volian.org/volian scar/main amd64 Packages
        500 https://deb.volian.org/volian scar/main all Packages
        100 /var/lib/dpkg/status
     0.15.0 500
        500 https://deb.volian.org/volian scar/main amd64 Packages
        500 https://deb.volian.org/volian scar/main all Packages
     0.14.0 500
        500 https://deb.volian.org/volian scar/main amd64 Packages
        500 https://deb.volian.org/volian scar/main all Packages
     0.12.2 500
        500 http://ftp.debian.org/debian bookworm/main amd64 Packages
```

**Comment by volitank** [comment]
Does this file exist?
```
/usr/lib/python3/dist-packages/debian/debian_support.py
```

If not I would try to reinstall `python3-debian`. Something definitely weird is going on.

**Comment by TheBrokenG0d** [comment]
> If not I would try to reinstall `python3-debian`. Something definitely weird is going on.

This fixed my issue, I did not even have a Debian folder under dist-packages just Debian-bundles.
