### ISSUE TITLE
Updated: Icons

### ISSUE THREAD

**Issue by nsrderooy** [volitank/nala#50]
This was tested on `Debian Sid` running `nala 0.15.3`

First of all I have checked and `apt update` does the same but I would still like to mention it,

This might be because of compatibility, a "bug" or it might be as intended but I would not understand why.

When I initially do a `nala update` I see the following lines;

```
Updated:   http://ftp.hk.debian.org/debian unstable/main Icons (48x48) [3.7 MB] 
Updated:   http://ftp.hk.debian.org/debian unstable/main Icons (64x64) [7.6 MB] 
Updated:   http://ftp.hk.debian.org/debian unstable/contrib Icons (48x48) [59 KB]
Updated:   http://ftp.hk.debian.org/debian unstable/contrib Icons (64x64) [129 KB]
Updated:   http://ftp.hk.debian.org/debian unstable/non-free Icons (48x48) [29 Bytes]
Updated:   http://ftp.hk.debian.org/debian unstable/non-free Icons (64x64) [27 KB]
Updated:   http://ftp.hk.debian.org/debian unstable/non-free-firmware Icons (48x48) [29 Bytes]
Updated:   http://ftp.hk.debian.org/debian unstable/non-free-firmware Icons (64x64) [29 Bytes]
Updated:   http://ossmirror.mycloud.services/debian sid/main Icons (48x48) [3.7 MB]
Updated:   http://ossmirror.mycloud.services/debian sid/main Icons (64x64) [7.6 MB]
Updated:   https://mirror.djvg.sg/debian sid/main Icons (48x48) [3.7 MB]        
Updated:   https://mirror.djvg.sg/debian sid/main Icons (64x64) [7.6 MB]        
Updated:   http://ftp.tw.debian.org/debian sid/main Icons (48x48) [3.7 MB]      
Updated:   https://opensource.nchc.org.tw/debian sid/main Icons (48x48) [3.7 MB]
Updated:   http://ftp.tw.debian.org/debian sid/main Icons (64x64) [7.6 MB]      
Updated:   https://opensource.nchc.org.tw/debian sid/main Icons (64x64) [7.6 MB]
```

It can be reproduced by running `rm -rf /var/lib/apt/lists/*; nala update`

Now while it's not a lot to most people, in this case it's roughly 56 MB that is probably wasted space/bandwidth.

Thanks in advance.

**Comment by volitank** [comment]
Take a look into this file `/etc/apt/apt.conf.d/60icons`

You can probably comment all of that out and it may work, or set the values in there to false

**Comment by nsrderooy** [comment]
Thanks for the info, so they are technically "required" if you use a GUI to install software and it's only installed if gnome is installed.

I'll just post the comments here for prosperity.

```
## This file enables the download of small-size 64x64px
## icons for use in software centers like GNOME Software
## and Plasma Discover.
##
## The icons are required for software centers to function
## correctly. Applications without an icon will not be
## displayed at all.

Acquire::IndexTargets {
    deb::DEP-11-icons-small  {
        DefaultEnabled "true";
    };
    deb::DEP-11-icons  {
        DefaultEnabled "true";
    };
};
```

**Comment by volitank** [comment]
Yea that seems to line up with what I was thinking. To me it isn't what I would call `required` if you use a GUI, but rather if you use `gnome-software` or `plasma-discover`. I do not use Gnome and have this file. I decided to just do some minor research, the file comes from `apt-config-icons`. And this is the `rdepends` of that pkg.

```
┌──[volitank@volidesk]─[/etc/aptro]
└──╼ > apt rdepends apt-config-icons
apt-config-icons
Reverse Depends:
  Recommends: apper
  Depends: plasma-discover
  Depends: gnome-software-plugin-deb
  Depends: apt-config-icons-large
  Depends: apt-config-icons-hidpi
  Suggests: appstream
  ```
  
 To me it seems if you are not going to use discover or gnome-software then it would be safe to comment all that out. Of course if you do use it then it seems necessary. Personally if I used either one I would comment it out, update, then see if it really doesn't work. It's pretty easy to reverse, just uncomment then update again.

**Comment by volitank** [comment]
No extremely on topic but you don't have to do `rm -rf /var/lib/apt/lists/*; nala update`, there is a nala command for this.

`nala clean --lists && nala update`.

`clean` with the `--lists` switch won't clean up the archives like just `nala clean` will.
