### ISSUE TITLE
Can't upgrade from 0.7.2 to 0.8.1

### ISSUE THREAD

**Issue by Booteille** [volitank/nala#6]
Hi!

When trying to upgrade nala to last version from nala's ppa I get the following error:
```console
The following packages were kept back:
nala
└── Depends:
    └── python3-typer is only referenced by name, no packages provides it
```

I am on Pop_OS! 21.10.

Edit: I upgraded Pop_OS! to 22.04 and Nala 0.8.1 installed properly on it. So maybe it's an issue specific to older versions of Ubuntu like distros.

Edit 2: I also read on Reddit that nala-legacy is the way to install nala on older debian versions, I guess it's probably bound to this issue.

**Comment by volitank** [comment]
Yes you are correct. With the release of 22.04 we had to change up the build method between that and older versions. So this will be the way forward.
